services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nistech\ContaoQualliIdClient\:
        resource: ../src/
        exclude:
            - ../src/{DependencyInjection,Session,Event}
            - ../src/**/*Exception.php

    Nistech\ContaoQualliIdClient\ButtonGenerator\ButtonGeneratorCollection:
        arguments:
            - !tagged_iterator contao_qualliid_client.button_generator

    Nistech\ContaoQualliIdClient\OAuth2\Client\ClientFactoryCollection:
        arguments:
            - !tagged_iterator contao_qualliid_client.client_factory

    Nistech\ContaoQualliIdClient\OAuth2\Token\TokenHandlerCollection:
        arguments:
            - !tagged_iterator contao_qualliid_client.token_handler

    # Add a session bag
    nistech.contao_qualliid_client.session.factory:
        class: Nistech\ContaoQualliIdClient\Session\SessionFactory
        decorates: session.factory
        arguments:
            - '@nistech.contao_qualliid_client.session.factory.inner'
            - '@nistech.contao_qualliid_client.session.attribute.array_attribute_bag_backend'
            - '@nistech.contao_qualliid_client.session.attribute.array_attribute_bag_frontend'

    nistech.contao_qualliid_client.session.attribute.array_attribute_bag_backend:
        class: Nistech\ContaoQualliIdClient\Session\Attribute\ArrayAttributeBag
        arguments:
            - _nistech_contao_qualliid_client_attr_backend
        calls:
            - [ setName, [ nistech_contao_qualliid_client_attr_backend ] ]

    nistech.contao_qualliid_client.session.attribute.array_attribute_bag_frontend:
        class: Nistech\ContaoQualliIdClient\Session\Attribute\ArrayAttributeBag
        arguments:
            - _nistech_contao_qualliid_client_attr_frontend
        calls:
            - [ setName, [ nistech_contao_qualliid_client_attr_frontend ] ]
